# Shell variables
# Generated by 'wal'
wallpaper='/home/plagus/Pictures/wallpapers/Cafe.jpg'

# Special
background='#150f14'
foreground='#9abfcf'
cursor='#9abfcf'

# Colors
color0='#150f14'
color1='#9B6A59'
color2='#CD7142'
color3='#AB8D6F'
color4='#E09F54'
color5='#37688D'
color6='#947B83'
color7='#9abfcf'
color8='#6b8590'
color9='#9B6A59'
color10='#CD7142'
color11='#AB8D6F'
color12='#E09F54'
color13='#37688D'
color14='#947B83'
color15='#9abfcf'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
