--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/plagus/Pictures/wallpapers/Cafe.jpg"

-- Special
background="#150f14"
foreground="#9abfcf"
cursor="#9abfcf"

-- Colors
color0="#150f14"
color1="#9B6A59"
color2="#CD7142"
color3="#AB8D6F"
color4="#E09F54"
color5="#37688D"
color6="#947B83"
color7="#9abfcf"
color8="#6b8590"
color9="#9B6A59"
color10="#CD7142"
color11="#AB8D6F"
color12="#E09F54"
color13="#37688D"
color14="#947B83"
color15="#9abfcf"
